### normal equation

#### 2 unknowns 1 equation

$W = (X^TX)^{-1}X^Ty $

In [1]:
import numpy as np
X = np.array([[1,1],[2,-1]])#2 dim, when you dot, it became (2,1)
y = np.array([14,10])

w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([8., 6.])

In [2]:
from sklearn.linear_model import LinearRegression

#model = LinearRegression()#fit_intercept is true WHEN default
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
display(model.coef_,model.intercept_)# different answer!!because of fit intercept，是否适应，计算截距，但是我们算出来的答案也是符合的

#linear regression is a packaging of normal equation

array([8., 6.])

0.0

In [3]:
from sklearn.linear_model import LinearRegression

#model = LinearRegression()#fit_intercept is true WHEN default
model = LinearRegression(fit_intercept=True)
model.fit(X,y)
display(model.coef_,model.intercept_)# different answer!!because of fit intercept，是否适应，计算截距，但是我们算出来的答案也是符合的

#linear regression is a packaging of normal equation

array([-0.8,  1.6])

13.2

### 多元

In [4]:
# 上面八元一次方程对应的X数据
X = np.array([[  0 ,14 , 8 ,  0 ,  5,  -2,   9,  -3],
 [ -4 , 10 ,  6 ,  4 ,-14 , -2 ,-14  , 8],
 [ -1 , -6  , 5 ,-12 ,  3 , -3 ,  2 , -2],
 [  5 , -2  , 3 , 10  , 5 , 11 ,  4  ,-8],
 [-15 ,-15  ,-8 ,-15 ,  7 , -4, -12 ,  2],
 [ 11 ,-10 , -2 ,  4  , 3 , -9 , -6 ,  7],
 [-14 ,  0 ,  4 , -3  , 5 , 10 , 13 ,  7],
 [ -3 , -7 , -2 , -8  , 0 , -6 , -5 , -9]])
# 对应的y
y = np.array([ 339 ,-114  , 30 , 126, -395 , -87 , 422, -309])
display(X,y)

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

array([ 339, -114,   30,  126, -395,  -87,  422, -309])

In [5]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w
#8 coef

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [6]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

#### add bias [12]

In [7]:
# 给了截距，意味着所有目标值y加了12 
y_new = y + 12
y_new

array([ 351, -102,   42,  138, -383,  -75,  434, -297])

In [8]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_new)
w

array([-0.97516868,  3.46580429, 18.35492506,  5.05194511,  8.91564723,
        2.19237439, 16.61633672, 11.36705945])

In [9]:
ones1 = np.ones(shape = (8,1))
ones1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [10]:
# we can consider b as wo*1
#他其实权重都相同，说明这个bias特征理论上并不重要
X_new = np.hstack((X,ones1))
display(X_new.shape,X_new)

(8, 9)

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

In [11]:
#array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.]) solution

In [12]:
w = np.array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])
b = 12
X9 = np.random.randint(-10,10,size = 8)
y9 = w.dot(X9)#ninth target
display(y9,X9)

127.0

array([-9,  7, -4,  4, -5, -6,  9,  5])

In [13]:
display(y_new)
y_new = np.hstack((y_new,[y9]))
display(y_new)

array([ 351, -102,   42,  138, -383,  -75,  434, -297])

array([ 351., -102.,   42.,  138., -383.,  -75.,  434., -297.,  127.])

In [14]:
display(X_new,X9)

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

array([-9,  7, -4,  4, -5, -6,  9,  5])

对于机器而言，其实不区分bias，都是需要求解的变量

In [15]:
display(X_new,y_new,w)
#现在需要将Xnew变方阵
X9 = np.hstack((X9,[1]))
X_new = np.vstack((X_new,X9))
display(X_new)

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

array([ 351., -102.,   42.,  138., -383.,  -75.,  434., -297.,  127.])

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.],
       [ -9.,   7.,  -4.,   4.,  -5.,  -6.,   9.,   5.,   1.]])

In [16]:
model = LinearRegression(fit_intercept=False)

model.fit(X_new,y_new)

display(model.coef_,model.intercept_)

array([-1.25198954,  3.25078601, 18.82511945,  5.33952622,  9.04397563,
        1.93903478, 16.56256612, 11.27835253, -1.68180587])

0.0

In [17]:
model = LinearRegression(fit_intercept=True)#我猜内部是去找不重要的数

model.fit(X_new,y_new)

display(model.coef_,model.intercept_)

array([-1.25198954,  3.25078601, 18.82511945,  5.33952622,  9.04397563,
        1.93903478, 16.56256612, 11.27835253,  0.        ])

-1.681805874572536

In [18]:
display(model.coef_,model.coef_.shape)
display(model.intercept_,model.intercept_.shape)

array([-1.25198954,  3.25078601, 18.82511945,  5.33952622,  9.04397563,
        1.93903478, 16.56256612, 11.27835253,  0.        ])

(9,)

-1.681805874572536

()

In [19]:
w = np.hstack((w,[12]))
w

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 12.])

In [20]:
w.shape

(9,)

In [21]:
y = X_new.dot(w) + b

In [22]:
display(y,y_new)

array([ 363.,  -90.,   54.,  150., -371.,  -63.,  446., -285.,  151.])

array([ 351., -102.,   42.,  138., -383.,  -75.,  434., -297.,  127.])

加截距和不加真的没什么差别
之所以true和false都能求，是因为是最后一列都是1，表明了都是截距，false能算出值，true就是0